# Generated by Django 3.2.9 on 2022-01-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_number', models.IntegerField(default=1)),
                ('goal', models.CharField(default='NC', max_length=200)),
                ('standard', models.CharField(blank=True, max_length=200, null=True)),
                ('concept_video', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['concept_number'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=200)),
                ('unit_number', models.IntegerField(default=1)),
                ('unit_blurb', models.TextField(blank=True, null=True)),
                ('concepts', models.ManyToManyField(related_name='concepts', to='preview.Concept')),
            ],
            options={
                'ordering': ['unit_number'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('Math 1', 'Math 1 Preview'), ('Math 2', 'Math 2 Preview'), ('Math 3', 'Math 3 Preview')], default='Math 2', max_length=200)),
                ('course_number', models.IntegerField(default=2)),
                ('price', models.IntegerField(default=199)),
                ('price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
                ('course_blurb', models.TextField(blank=True, null=True)),
                ('course_initials', models.CharField(blank=True, max_length=100, null=True)),
                ('course_color', models.CharField(blank=True, max_length=100, null=True)),
                ('is_available_for_purchase', models.BooleanField(default=False)),
                ('units', models.ManyToManyField(related_name='units', to='preview.Unit')),
            ],
            options={
                'ordering': ['course_number'],
            },
        ),
    ]
