# Generated by Django 3.2.9 on 2022-02-02 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preview', '0003_auto_20220201_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concept',
            options={'ordering': ['concepts__unit_name', 'concept_number']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_number']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['units__course_number', 'unit_number']},
        ),
    ]
