# Generated by Django 3.2.9 on 2022-02-02 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preview', '0004_auto_20220201_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concept',
            options={'ordering': ['concepts__unit_name', 'concept_number'], 'verbose_name_plural': '  Concepts'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_number'], 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['units__course_number', 'unit_number'], 'verbose_name_plural': ' Units'},
        ),
    ]
